import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from 'vitest';
import { buildDayDefinitions } from './buildDayDefinitions';
import { questionById, REWIND_QUESTION_BANK } from '../src/data/questionBank';
import { DAY_DEFINITIONS as PREVIOUS_DAYS } from '../src/data/dayDefinitions';

const here = dirname(fileURLToPath(import.meta.url));

// A day's identity = its set of 5 ids (order-independent).
const daySignature = (day: string[]) => [...day].sort().join(',');

const days = buildDayDefinitions();

test('produces 10 days of 5 unique ids, all eligible', () => {
  expect(days).toHaveLength(10);
  const all = days.flat();
  expect(all).toHaveLength(50);
  expect(new Set(all).size).toBe(50); // no cross-day repeats
  for (const id of all) {
    const q = questionById.get(id);
    expect(q?.eligibleForMain).toBe(true);
  }
});

test('each day follows the E E M H H curve', () => {
  for (const day of days) {
    const diffs = day.map((id) => questionById.get(id)!.difficulty);
    expect(diffs).toEqual(['easy', 'easy', 'medium', 'hard', 'hard']);
  }
});

test('no repeated primary team or player within a day', () => {
  for (const day of days) {
    const qs = day.map((id) => questionById.get(id)!);
    const teams = qs.map((q) => q.teams[0]);
    const players = qs.map((q) => q.players[0]);
    expect(new Set(teams).size).toBe(teams.length);
    expect(new Set(players).size).toBe(players.length);
  }
});

test('determinism: two runs are identical', () => {
  expect(buildDayDefinitions()).toEqual(days);
});

test('a seeded run is valid and differs from the default arrangement', () => {
  const seeded = buildDayDefinitions(REWIND_QUESTION_BANK, { seed: 1234 });
  expect(seeded.flat()).toHaveLength(50);
  expect(new Set(seeded.flat()).size).toBe(50);
  for (const day of seeded) {
    const diffs = day.map((id) => questionById.get(id)!.difficulty);
    expect(diffs).toEqual(['easy', 'easy', 'medium', 'hard', 'hard']);
  }
  expect(seeded).not.toEqual(days); // randomization actually changed the layout
});

test.runIf(process.env.WRITE_DAYS === '1')('writes src/data/dayDefinitions.ts', () => {
  const wantRandom = process.env.RANDOM_DAYS === '1' || process.env.SEED !== undefined;
  let generated: string[][];

  if (!wantRandom) {
    generated = buildDayDefinitions();
  } else {
    // Randomized: find a seed whose 10 days reuse no previous day's exact lineup.
    const prevSigs = new Set(PREVIOUS_DAYS.map(daySignature));
    const baseSeed = process.env.SEED !== undefined ? Number(process.env.SEED) : Date.now();
    let best: string[][] | null = null;
    let bestRepeats = Infinity;
    for (let attempt = 0; attempt < 200; attempt++) {
      const candidate = buildDayDefinitions(REWIND_QUESTION_BANK, { seed: baseSeed + attempt });
      const repeats = candidate.filter((d) => prevSigs.has(daySignature(d))).length;
      if (repeats < bestRepeats) {
        best = candidate;
        bestRepeats = repeats;
      }
      if (repeats === 0) break;
    }
    generated = best!;
    if (bestRepeats > 0) {
      console.warn(
        `[buildDayDefinitions] could not avoid all previous days; ${bestRepeats} day(s) reused.`,
      );
    }
  }

  const body = generated
    .map(
      (day, i) =>
        `  // Day ${i + 1}\n  [\n${day.map((id) => `    '${id}',`).join('\n')}\n  ],`,
    )
    .join('\n');
  const file =
    `// AUTO-GENERATED by scripts/buildDayDefinitions.ts — do not edit by hand.\n` +
    `// Regenerate: WRITE_DAYS=1 npx vitest run scripts/buildDayDefinitions.test.ts\n\n` +
    `export const DAY_DEFINITIONS: string[][] = [\n${body}\n];\n`;
  writeFileSync(resolve(here, '../src/data/dayDefinitions.ts'), file);
});
