// AUTO-GENERATED by scripts/buildDayDefinitions.ts — do not edit by hand.
// Regenerate: WRITE_DAYS=1 npx vitest run scripts/buildDayDefinitions.test.ts

export const DAY_DEFINITIONS: string[][] = [
  // Day 1
  [
    'evt_warriors_73_9',
    'evt_lebron_returns_cleveland',
    'evt_jordan_flu_game',
    'evt_nova_knicks_ncaa',
    'evt_lillard_wave_okc',
  ],
  // Day 2
  [
    'evt_linsanity',
    'evt_curry_unanimous_mvp',
    'evt_westbrook_triple_double_record',
    'evt_malice_palace',
    'evt_tmac_13_35',
  ],
  // Day 3
  [
    'evt_vince_dunk_contest',
    'evt_carmelo_62_msg',
    'evt_kobe_81',
    'evt_we_believe_warriors',
    'evt_dr_j_dunk',
  ],
  // Day 4
  [
    'evt_lebron_scoring_record',
    'evt_bulls_72_10',
    'evt_jokic_nuggets_title',
    'evt_klay_37_quarter',
    'evt_chris_paul_veto',
  ],
  // Day 5
  [
    'evt_raptors_first_title',
    'evt_kd_joins_warriors',
    'evt_celtics_big_three',
    'evt_phil_lakers_hired',
    'evt_luka_60_21_10',
  ],
  // Day 6
  [
    'evt_tim_duncan_drafted',
    'evt_shaq_kobe_first',
    'evt_luka_trae_trade',
    'evt_lebron_game6_boston',
    'evt_wilt_100',
  ],
  // Day 7
  [
    'evt_lakers_bubble_title',
    'evt_wemby_drafted',
    'evt_harden_rockets_trade',
    'evt_dirk_upsets_heat',
    'evt_reggie_8_9',
  ],
  // Day 8
  [
    'evt_jordan_last_shot',
    'evt_lebron_drafted',
    'evt_ray_allen_game6',
    'evt_knicks_4_point_play',
    'evt_kobe_final_60',
  ],
  // Day 9
  [
    'evt_kobe_drafted',
    'evt_the_decision',
    'evt_jordan_drafted',
    'evt_bird_steal',
    'evt_magic_baby_hook',
  ],
  // Day 10
  [
    'evt_curry_3pt_record',
    'evt_rose_youngest_mvp',
    'evt_iverson_stepover',
    'evt_cavs_3_1_comeback',
    'evt_magic_center_finals',
  ],
];
